# PYQS 2020

## Group - D

In [2]:
import numpy as np

In [ ]:
a = np.random.rand(2, 3) * 100
print(a)

b = np.array([2.5, 6.0, 9.4])
print(b)

[[22.92254614 46.25803481  9.99154959]
 [37.22506486 83.94746026 89.6257757 ]]
[2.5 6.  9.4]


In [9]:
print(a + b)

[[25.42254614 52.25803481 19.39154959]
 [39.72506486 89.94746026 99.0257757 ]]


In [11]:
x = [1, 2, 3, 4, 5]
y = [10, 20, 30, 40, 50]
barray = [True, False, False, True, True]

z1 = [x[i] if barray[i] else y[i] for i in range(len(x))]
print(z1)

z2 = np.where(barray, x, y)
print(z2)

[1, 20, 30, 4, 5]
[ 1 20 30  4  5]


In [16]:
from datetime import datetime, timedelta

start_time = input("Enter start time: ")
duration = float(input("Enter duration in minutes: "))

start_dt = datetime.strptime(start_time, "%H:%M")
end_dt = start_dt + timedelta(minutes=duration)

print("End Time: ", end_dt.strftime("%H:%M:%S"))

End Time:  10:16:53


## Misc

In [2]:
matrix = [[4, 5, 6], [8, 2, 1], [12, 8, 0]]
print(matrix)
res = [[x for x in row if x % 4 == 0] for row in matrix if sum(row) <= 15]
print(res)

[[4, 5, 6], [8, 2, 1], [12, 8, 0]]
[[4], [8]]
