# PYQS 2021

## Group - D

In [2]:
import pandas as pd
import numpy as np

In [4]:
# 6a
a = np.ones((3, 2))
b = np.array([0, 1, 2])

print(a)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [6]:
# Addition not possible
a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [10]:
c = np.ones((3, 2, 1))
print(b.shape)
print(c.shape)
print(c + b)

(3,)
(3, 2, 1)
[[[1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]]]


In [21]:
x = int(input("Enter x-coord: "))
y = int(input("Enter y-coord: "))
print(f"({x}, {y})")

if x > 0 and y > 0:
    print("1st Quad.")
elif x < 0 and y > 0:
    print("2nd Quad.")
elif x > 0 and y < 0:
    print("4th Quad.")
elif x < 0 and y < 0:
    print("3rd Quad.")
elif x == 0 and y == 0:
    print("Origin")
elif x == 0:
    print("Y-axis")
elif y == 0:
    print("X-axis")

(-9, -5)
3rd Quad.


In [25]:
df = pd.DataFrame({
    "M0": [8, np.nan, np.nan, 7],
    "M1": [2, 2, np.nan, 3],
    "M2": [np.nan, 3, np.nan, 7]
})
print(df)

df2 = df.fillna(0)
print(df2)

df3 = df.ffill()
print(df3)

df4 = df.fillna(df.mean(numeric_only=True))
print(df4)

    M0   M1   M2
0  8.0  2.0  NaN
1  NaN  2.0  3.0
2  NaN  NaN  NaN
3  7.0  3.0  7.0
    M0   M1   M2
0  8.0  2.0  0.0
1  0.0  2.0  3.0
2  0.0  0.0  0.0
3  7.0  3.0  7.0
    M0   M1   M2
0  8.0  2.0  NaN
1  8.0  2.0  3.0
2  8.0  2.0  3.0
3  7.0  3.0  7.0
    M0        M1   M2
0  8.0  2.000000  5.0
1  7.5  2.000000  3.0
2  7.5  2.333333  5.0
3  7.0  3.000000  7.0


In [28]:
data = {
    "City": ["Delhi", "Kolkata", "Mumbai"],
    "2020": [3.029, 1.485, 2.0411],
    "2019": [2.94, 1.4755, 2.0185]
}

df = pd.DataFrame(data)
print(df)

df['2018'] = [2.85, 1.468, 1.998]
print(df)

df["Average"] = df[["2020", "2019", "2018"]].mean(axis=1)
print(df)

      City    2020    2019
0    Delhi  3.0290  2.9400
1  Kolkata  1.4850  1.4755
2   Mumbai  2.0411  2.0185
      City    2020    2019   2018
0    Delhi  3.0290  2.9400  2.850
1  Kolkata  1.4850  1.4755  1.468
2   Mumbai  2.0411  2.0185  1.998
      City    2020    2019   2018   Average
0    Delhi  3.0290  2.9400  2.850  2.939667
1  Kolkata  1.4850  1.4755  1.468  1.476167
2   Mumbai  2.0411  2.0185  1.998  2.019200


## Misc

In [2]:
import math

class RegTooSmall(Exception):
    pass

class RegTooHigh(Exception):
    pass

def find_n(n):
    res = math.ceil(math.log2(n))
    return res

def check_range(n):
    if n > 255:
        raise RegTooHigh("Too many reg.")
    elif n < 1:
        raise RegTooSmall("Too less reg.")
    else:
        return find_n(n)

while True:
    try:
        n = int(input("Enter no. of reg.: "))
        res = check_range(n)
        print(res)
        break
    except ValueError as e:
        print(e)
    except RegTooSmall as e:
        print(e)
    except RegTooHigh as e:
        print(e)
    except Exception as e:
        print(e)

Too many reg.
invalid literal for int() with base 10: ''
Too less reg.
6


In [6]:
import re

s = input("Enter a number: ")

pattern = r'^[+-]?\d+(\.\d+)?$'
if re.match(pattern, s):
    num = float(s)
    print(num ** 2.0)
else:
    print("Invalid")

64.0


In [7]:
with open('sample.txt', 'r') as f:
    char_count = [len(line) for line in f]

print(char_count)

[11, 22, 11, 1, 9, 8, 5]


In [8]:
with open('sample.txt', 'r') as f:
    for i, line in enumerate(f, start=1):
        print(f'Line {i} has {len(line)} chars.')

Line 1 has 11 chars.
Line 2 has 22 chars.
Line 3 has 11 chars.
Line 4 has 1 chars.
Line 5 has 9 chars.
Line 6 has 8 chars.
Line 7 has 5 chars.


In [9]:
triplets = [(x, y, z) for x in range(51) for y in range(51) for z in range(51) if x ** 2 + y ** 2 == z ** 2]
triplets

[(0, 0, 0),
 (0, 1, 1),
 (0, 2, 2),
 (0, 3, 3),
 (0, 4, 4),
 (0, 5, 5),
 (0, 6, 6),
 (0, 7, 7),
 (0, 8, 8),
 (0, 9, 9),
 (0, 10, 10),
 (0, 11, 11),
 (0, 12, 12),
 (0, 13, 13),
 (0, 14, 14),
 (0, 15, 15),
 (0, 16, 16),
 (0, 17, 17),
 (0, 18, 18),
 (0, 19, 19),
 (0, 20, 20),
 (0, 21, 21),
 (0, 22, 22),
 (0, 23, 23),
 (0, 24, 24),
 (0, 25, 25),
 (0, 26, 26),
 (0, 27, 27),
 (0, 28, 28),
 (0, 29, 29),
 (0, 30, 30),
 (0, 31, 31),
 (0, 32, 32),
 (0, 33, 33),
 (0, 34, 34),
 (0, 35, 35),
 (0, 36, 36),
 (0, 37, 37),
 (0, 38, 38),
 (0, 39, 39),
 (0, 40, 40),
 (0, 41, 41),
 (0, 42, 42),
 (0, 43, 43),
 (0, 44, 44),
 (0, 45, 45),
 (0, 46, 46),
 (0, 47, 47),
 (0, 48, 48),
 (0, 49, 49),
 (0, 50, 50),
 (1, 0, 1),
 (2, 0, 2),
 (3, 0, 3),
 (3, 4, 5),
 (4, 0, 4),
 (4, 3, 5),
 (5, 0, 5),
 (5, 12, 13),
 (6, 0, 6),
 (6, 8, 10),
 (7, 0, 7),
 (7, 24, 25),
 (8, 0, 8),
 (8, 6, 10),
 (8, 15, 17),
 (9, 0, 9),
 (9, 12, 15),
 (9, 40, 41),
 (10, 0, 10),
 (10, 24, 26),
 (11, 0, 11),
 (12, 0, 12),
 (12, 5, 13),
 (12, 9

In [10]:
import math

class Point:
    def __init__(self, x = 0, y = 0):
        self.x = x
        self.y = y
    
    def dist(self):
        dist = math.sqrt(self.x ** 2 + self.y ** 2)
        print(dist)
    
    def display(self):
        print(f'({self.x}, {self.y})')

ob = Point(9, 8)
ob.display()
ob.dist()

(9, 8)
12.041594578792296
