# PYQS 2021

## Group - D

In [2]:
import pandas as pd
import numpy as np

In [4]:
# 6a
a = np.ones((3, 2))
b = np.array([0, 1, 2])

print(a)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [6]:
# Addition not possible
a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [10]:
c = np.ones((3, 2, 1))
print(b.shape)
print(c.shape)
print(c + b)

(3,)
(3, 2, 1)
[[[1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]]]


In [21]:
x = int(input("Enter x-coord: "))
y = int(input("Enter y-coord: "))
print(f"({x}, {y})")

if x > 0 and y > 0:
    print("1st Quad.")
elif x < 0 and y > 0:
    print("2nd Quad.")
elif x > 0 and y < 0:
    print("4th Quad.")
elif x < 0 and y < 0:
    print("3rd Quad.")
elif x == 0 and y == 0:
    print("Origin")
elif x == 0:
    print("Y-axis")
elif y == 0:
    print("X-axis")

(-9, -5)
3rd Quad.


In [25]:
df = pd.DataFrame({
    "M0": [8, np.nan, np.nan, 7],
    "M1": [2, 2, np.nan, 3],
    "M2": [np.nan, 3, np.nan, 7]
})
print(df)

df2 = df.fillna(0)
print(df2)

df3 = df.ffill()
print(df3)

df4 = df.fillna(df.mean(numeric_only=True))
print(df4)

    M0   M1   M2
0  8.0  2.0  NaN
1  NaN  2.0  3.0
2  NaN  NaN  NaN
3  7.0  3.0  7.0
    M0   M1   M2
0  8.0  2.0  0.0
1  0.0  2.0  3.0
2  0.0  0.0  0.0
3  7.0  3.0  7.0
    M0   M1   M2
0  8.0  2.0  NaN
1  8.0  2.0  3.0
2  8.0  2.0  3.0
3  7.0  3.0  7.0
    M0        M1   M2
0  8.0  2.000000  5.0
1  7.5  2.000000  3.0
2  7.5  2.333333  5.0
3  7.0  3.000000  7.0


In [28]:
data = {
    "City": ["Delhi", "Kolkata", "Mumbai"],
    "2020": [3.029, 1.485, 2.0411],
    "2019": [2.94, 1.4755, 2.0185]
}

df = pd.DataFrame(data)
print(df)

df['2018'] = [2.85, 1.468, 1.998]
print(df)

df["Average"] = df[["2020", "2019", "2018"]].mean(axis=1)
print(df)

      City    2020    2019
0    Delhi  3.0290  2.9400
1  Kolkata  1.4850  1.4755
2   Mumbai  2.0411  2.0185
      City    2020    2019   2018
0    Delhi  3.0290  2.9400  2.850
1  Kolkata  1.4850  1.4755  1.468
2   Mumbai  2.0411  2.0185  1.998
      City    2020    2019   2018   Average
0    Delhi  3.0290  2.9400  2.850  2.939667
1  Kolkata  1.4850  1.4755  1.468  1.476167
2   Mumbai  2.0411  2.0185  1.998  2.019200
