# PYQs 2022

## Group - D

In [11]:
import numpy as np
import pandas as pd

In [4]:
arr = np.array([1, 7, 5, -4, 8, -3])
arr[1:6:2]

array([ 7, -4, -3])

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
idx = [0, 2, 4]
print(a[idx])

b = np.array([[1, 2, 3], [4, 5, 6]])
rows = [0, 1]
cols = [1, 2]
print(b[rows, cols])

[1 3 5]
[2 6]


In [10]:
m = np.matrix('2 1 8; 0 5 6; 7 9 3')
print(m)
np.sort(m)

[[2 1 8]
 [0 5 6]
 [7 9 3]]


matrix([[1, 2, 8],
        [0, 5, 6],
        [3, 7, 9]])

In [13]:
df = pd.DataFrame({
    "M0": [8, np.nan, np.nan, 7],
    "M1": [2, 2, np.nan, 3],
    "M2": [np.nan, 3, np.nan, 7]
})
print(df)

print(df.isna())
print(df.notna())
print(df.interpolate())
print(df.dropna())

    M0   M1   M2
0  8.0  2.0  NaN
1  NaN  2.0  3.0
2  NaN  NaN  NaN
3  7.0  3.0  7.0
      M0     M1     M2
0  False  False   True
1   True  False  False
2   True   True   True
3  False  False  False
      M0     M1     M2
0   True   True  False
1  False   True   True
2  False  False  False
3   True   True   True
         M0   M1   M2
0  8.000000  2.0  NaN
1  7.666667  2.0  3.0
2  7.333333  2.5  5.0
3  7.000000  3.0  7.0
    M0   M1   M2
3  7.0  3.0  7.0
