# Numpy Basics

## Fundamentals

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [20]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [21]:
# dimension
a.ndim, b.ndim

(1, 2)

In [8]:
#shape
a.shape, b.shape

((3,), (2, 3))

In [22]:
# type
a.dtype, b.dtype

(dtype('int32'), dtype('float64'))

In [12]:
# explicit typing
c = np.array([1, 2, 3], dtype='int16')
print(c)

c.dtype

[1 2 3]


dtype('int16')

In [23]:
# size of element in bytes
a.itemsize, b.itemsize

(4, 8)

In [24]:
# total size(or no. of elements)
a.size, b.size

(3, 6)

In [25]:
# size in bytes
a.nbytes, b.nbytes

(12, 48)

In [26]:
# bytes without using nbytes
a.itemsize * a.size

12

## Accessing/modifying elements, rows, cols.

In [38]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
print(a[1, 5])
print(a[1, -2]) # -ve indexing

13
13


In [39]:
a[0, :] # row

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:, 3] # col

array([ 4, 11])

In [ ]:
a[0, 1:6:2] # 1st row, start_idx:end_idx:step_size

array([2, 4, 6])

In [ ]:
a[1, 5] = 20
print(a)

a[:, 2] = 5 # col idx = 2 --> all ele = 5
print("\n", a)

a[:, 2] = [1, 2] # col idx = 2 --> [1, 2]
print("\n", a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]

 [[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]

 [[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [41]:
# 3-D
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [44]:
print(b[0, 1, 1])
print(b[:, 1, :])

4
[[3 4]
 [7 8]]


In [45]:
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Different types of arrays

In [50]:
# 0 matrices
print(np.zeros(5))
print(np.zeros((2, 3, 3)))

[0. 0. 0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [51]:
# 1s matrix
np.ones((4, 2, 3), dtype='int16')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [52]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full_like(a, 4) # transforms full array a with val = 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [54]:
# random matrix
np.random.rand(4, 2)

array([[0.13159313, 0.99112139],
       [0.22147526, 0.44448703],
       [0.6739451 , 0.744573  ],
       [0.84850789, 0.65220728]])

In [55]:
np.random.random_sample(a.shape)

array([[0.28254921, 0.58346915, 0.26470232, 0.28408922, 0.14765807,
        0.23680058, 0.14605896],
       [0.43825455, 0.55340635, 0.12517   , 0.51194697, 0.31653234,
        0.15954308, 0.79816037]])

In [61]:
np.random.randint(7, size=(3, 3)) # random nos. b/w 0-6 (7 exclusive)

array([[4, 3, 3],
       [5, 4, 3],
       [0, 5, 6]])

In [62]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [67]:
arr = np.array([[1, 2, 3]])
r2 = np.repeat(arr, 3, axis=0)
r2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Q. Generate an array like:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

In [71]:
res = np.ones((5, 5), dtype='int32')
print(res)

helper = np.zeros((3, 3), dtype='int32')
helper[1, 1] = 9
print(helper)

res[1:-1, 1:-1] = helper #1:-1 index 1 row to last - 1 row, index 1 col to last - 1 col
print("\n", res)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]

 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# Shallow copy
x = np.array([1, 2, 3])
y = x # y points to same object in mem. as x
print(x, y)

y[0] = 100 # changes value o f x as well
print(x, y)

[1 2 3] [1 2 3]
[100   2   3] [100   2   3]


In [ ]:
# Deep copy
x = np.array([1, 2, 3])
y = x.copy() # new object in mem. for y
print(x, y)

y[0] = 100 # doesn't change value o f x
print(x, y)

[1 2 3] [1 2 3]
[1 2 3] [100   2   3]


## Mathematics in Numpy

In [83]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [88]:
print(a + 2, "\n")
print(a - 2, "\n")
print(a * 2, "\n")
print(a / 2, "\n")
print(a ** 2, "\n")
print(np.sin(a), "\n")
print(np.cos(a), "\n")

[5 6 7 8] 

[1 2 3 4] 

[ 6  8 10 12] 

[1.5 2.  2.5 3. ] 

[ 9 16 25 36] 

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ] 

[-0.9899925  -0.65364362  0.28366219  0.96017029] 



In [85]:
a += 2
a

array([3, 4, 5, 6])

In [86]:
b = np.array([1, 0, 1, 0])
a + b

array([4, 4, 6, 6])