# Numpy Basics

## Fundamentals

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [20]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [21]:
# dimension
a.ndim, b.ndim

(1, 2)

In [8]:
#shape
a.shape, b.shape

((3,), (2, 3))

In [22]:
# type
a.dtype, b.dtype

(dtype('int32'), dtype('float64'))

In [12]:
# explicit typing
c = np.array([1, 2, 3], dtype='int16')
print(c)

c.dtype

[1 2 3]


dtype('int16')

In [23]:
# size of element in bytes
a.itemsize, b.itemsize

(4, 8)

In [24]:
# total size(or no. of elements)
a.size, b.size

(3, 6)

In [25]:
# size in bytes
a.nbytes, b.nbytes

(12, 48)

In [26]:
# bytes without using nbytes
a.itemsize * a.size

12

## Accessing/modifying elements, rows, cols.

In [38]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
print(a[1, 5])
print(a[1, -2]) # -ve indexing

13
13


In [39]:
a[0, :] # row

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[:, 3] # col

array([ 4, 11])

In [ ]:
a[0, 1:6:2] # 1st row, start_idx:end_idx:step_size

array([2, 4, 6])

In [ ]:
a[1, 5] = 20
print(a)

a[:, 2] = 5 # col idx = 2 --> all ele = 5
print("\n", a)

a[:, 2] = [1, 2] # col idx = 2 --> [1, 2]
print("\n", a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]

 [[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]

 [[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [41]:
# 3-D
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [44]:
print(b[0, 1, 1])
print(b[:, 1, :])

4
[[3 4]
 [7 8]]


In [45]:
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
